#!/usr/bin/env python3
"""
UK-EU AI Compliance OS — Gap Analysis Report Generator
Generates a markdown compliance report from a JSON config.
Usage: python generate-compliance-report.py --config client-config.json
"""

import json
import argparse
from datetime import datetime

TEMPLATE = """# AI Compliance Gap Analysis Report
**Generated:** {date}  
**Client Sector:** {sector}  
**AI Systems in Scope:** {system_count}  
**EU Exposure:** {eu_exposure}  
**Target Certification Date:** {target_date}

---

## Executive Summary

| Area | Status | Gap Severity |
|------|--------|--------------|
| Leadership & Governance | {leadership_status} | {leadership_gap} |
| AI System Inventory | {inventory_status} | {inventory_gap} |
| Risk Management | {risk_status} | {risk_gap} |
| Data Governance | {data_status} | {data_gap} |
| Human Oversight | {oversight_status} | {oversight_gap} |
| Transparency & Documentation | {transparency_status} | {transparency_gap} |
| Certification Readiness | {cert_status} | {cert_gap} |

---

## Recommended Sprint

{recommendation}

---

*Report generated by UK-EU AI Compliance OS*  
*For implementation architecture: compliance.architect@protonmail.com*
"""

def main():
    parser = argparse.ArgumentParser(description="Generate compliance gap report")
    parser.add_argument("--config", required=True, help="Path to JSON config file")
    parser.add_argument("--output", default="compliance-report.md", help="Output markdown file")
    args = parser.parse_args()

    with open(args.config, "r") as f:
        data = json.load(f)

    report = TEMPLATE.format(
        date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        sector=data.get("sector", "Unknown"),
        system_count=data.get("system_count", 0),
        eu_exposure=data.get("eu_exposure", "Unknown"),
        target_date=data.get("target_date", "Not set"),
        leadership_status=data.get("leadership_status", "Not assessed"),
        leadership_gap=data.get("leadership_gap", "Unknown"),
        inventory_status=data.get("inventory_status", "Not assessed"),
        inventory_gap=data.get("inventory_gap", "Unknown"),
        risk_status=data.get("risk_status", "Not assessed"),
        risk_gap=data.get("risk_gap", "Unknown"),
        data_status=data.get("data_status", "Not assessed"),
        data_gap=data.get("data_gap", "Unknown"),
        oversight_status=data.get("oversight_status", "Not assessed"),
        oversight_gap=data.get("oversight_gap", "Unknown"),
        transparency_status=data.get("transparency_status", "Not assessed"),
        transparency_gap=data.get("transparency_gap", "Unknown"),
        cert_status=data.get("cert_status", "Not assessed"),
        cert_gap=data.get("cert_gap", "Unknown"),
        recommendation=data.get("recommendation", "Engage diagnostic review.")
    )

    with open(args.output, "w") as f:
        f.write(report)

    print(f"✅ Compliance report generated: {args.output}")

if __name__ == "__main__":
    main()
