#!/usr/bin/env python3
"""
LangChain Observability Template for EU AI Act Transparency
UK-EU AI Compliance OS

Provides structured logging of LLM chain inputs, outputs, and metadata
to satisfy EU AI Act Article 52 (transparency) and Article 13 (deployer info).

Usage:
    from langchain_observability import ObservableLLMChain
    chain = ObservableLLMChain(
        llm=your_llm,
        prompt=your_prompt,
        system_id="customer_support_bot_v1"
    )
    result = chain.run(user_input="How do I reset my password?")
"""

import json
import uuid
import datetime
from typing import Dict, Any, Optional, List
from pathlib import Path


class ObservableLLMChain:
    """
    Wrapper for LangChain LLM chains with EU AI Act transparency logging.
    Generates records satisfying:
    - Article 13: Information to deployers
    - Article 52: Transparency to users
    - ISO 42001 Clause 8.5: AI system deployment records
    """
    
    def __init__(
        self,
        llm,
        prompt,
        system_id: str,
        system_version: str = "1.0.0",
        output_dir: str = "llm_transparency_logs",
        log_retention_days: int = 365
    ):
        self.llm = llm
        self.prompt = prompt
        self.system_id = system_id
        self.system_version = system_version
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        self.log_retention_days = log_retention_days
        
    def _generate_interaction_id(self) -> str:
        return f"llm_{uuid.uuid4().hex[:12]}"
    
    def _get_system_metadata(self) -> Dict[str, Any]:
        return {
            "system_id": self.system_id,
            "system_version": self.system_version,
            "model_provider": getattr(self.llm, "model_provider", "unknown"),
            "model_name": getattr(self.llm, "model_name", "unknown"),
            "temperature": getattr(self.llm, "temperature", "unknown"),
            "max_tokens": getattr(self.llm, "max_tokens", "unknown"),
            "system_capabilities": "documented_in_technical_file",
            "known_limitations": "documented_in_instructions_for_use",
            "training_data_cutoff": "documented_in_model_card"
        }
    
    def run(
        self,
        user_input: str,
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Execute LLM chain with full transparency logging.
        Returns the LLM output. Log file contains complete audit trail.
        """
        
        interaction_id = self._generate_interaction_id()
        timestamp = datetime.datetime.utcnow().isoformat()
        
        # Execute the actual chain
        chain_input = self.prompt.format(input=user_input)
        llm_output = self.llm(chain_input) if callable(self.llm) else "LLM_EXECUTION_PLACEHOLDER"
        
        # Build transparency record
        record = {
            "interaction_id": interaction_id,
            "timestamp_utc": timestamp,
            "regulatory_scope": {
                "eu_ai_act_articles": ["Article 13", "Article 52"],
                "iso_42001_clauses": ["8.5", "8.6"],
                "transparency_type": "user_facing_chatbot"  # Modify per deployment
            },
            
            "system_metadata": self._get_system_metadata(),
            
            "input_record": {
                "raw_user_input": user_input,
                "processed_prompt": chain_input,
                "prompt_template_version": "1.0",
                "system_prompt_included": True,
                "user_id_hash": self._hash_id(user_id) if user_id else None,
                "session_id": session_id
            },
            
            "output_record": {
                "llm_raw_output": llm_output,
                "output_filtered": False,  # Set True if content moderation applied
                "filter_reason": None,
                "confidence_score": None  # Add if your model provides this
            },
            
            "human_oversight": {
                "human_review_required": False,  # Set True for high-risk systems
                "reviewer_id": None,
                "review_timestamp": None,
                "override_applied": False
            },
            
            "eu_ai_act_disclosures": {
                "ai_system_notification": "This response was generated by an artificial intelligence system.",
                "human_chat_available": True,  # Set per your deployment
                "data_used_for_training": False,  # EU AI Act requires this disclosure
                "rights_information": "You have the right to contest automated decisions with legal effects."
            },
            
            "retention": {
                "log_retention_days": self.log_retention_days,
                "deletion_date": (datetime.datetime.utcnow() + 
                    datetime.timedelta(days=self.log_retention_days)).isoformat()
            }
        }
        
        # Save transparency log
        log_file = self.output_dir / f"{interaction_id}.json"
        with open(log_file, "w") as f:
            json.dump(record, f, indent=2)
        
        print(f"[TRANSPARENCY] Logged interaction: {interaction_id}")
        print(f"[TRANSPARENCY] File: {log_file}")
        print(f"[TRANSPARENCY] EU AI Act disclosure included: {record['eu_ai_act_disclosures']['ai_system_notification']}")
        
        return llm_output
    
    def _hash_id(self, user_id: str) -> str:
        """Hash user ID for pseudonymization compliance."""
        import hashlib
        return hashlib.sha256(user_id.encode()).hexdigest()[:16]
    
    def generate_transparency_report(self, date_range: Optional[tuple] = None) -> str:
        """
        Generate aggregate transparency report for regulator or deployer.
        Satisfies EU AI Act Article 13 requirement for system documentation.
        """
        # Placeholder for batch reporting logic
        return "Transparency report generation: implement based on your logging volume."


# Example usage
if __name__ == "__main__":
    print("=" * 60)
    print("LangChain Observability Template")
    print("EU AI Act Article 52 + ISO 42001 Clause 8.5 Ready")
    print("=" * 60)
    print()
    print("This is a template. Integrate with your actual LangChain setup:")
    print()
    print("  from langchain import OpenAI, PromptTemplate")
    print("  llm = OpenAI(temperature=0.7)")
    print("  prompt = PromptTemplate(")
    print("      input_variables=['input'],")
    print("      template='You are a helpful assistant. User: {input}')")
    print("  chain = ObservableLLMChain(llm=llm, prompt=prompt, system_id='support_bot_v1')")
    print("  result = chain.run(user_input='Hello world')")
    print()
    print("All interactions are logged with EU AI Act transparency disclosures.")
    print("Logs stored in: ./llm_transparency_logs/")
